# Generated by Django 6.0.3 on 2026-03-14 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('hsn_code', models.CharField(blank=True, max_length=20)),
                ('stock_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_meter', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
