# Generated by Django 6.0.3 on 2026-03-18 08:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('party_type', models.CharField(choices=[('CLIENT', 'Client / Buyer'), ('PRODUCTION', 'Production / Job Worker')], max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ordered_qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivered_qty', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_bill', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_received', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PARTIAL', 'Partially Delivered'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('client', models.ForeignKey(limit_choices_to={'party_type': 'CLIENT'}, on_delete=django.db.models.deletion.CASCADE, to='core_app.party')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('given_qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('received_qty', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('job_rate_per_meter', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('production_company', models.ForeignKey(limit_choices_to={'party_type': 'PRODUCTION'}, on_delete=django.db.models.deletion.CASCADE, to='core_app.party')),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_jobs', to='core_app.salesorder')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
